/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsCronRouteImport } from './routes/settings.cron'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as SettingsCronIndexRouteImport } from './routes/settings.cron.index'
import { Route as SettingsCronJobIdRouteImport } from './routes/settings.cron.$jobId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCronRoute = SettingsCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsCronIndexRoute = SettingsCronIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsCronRoute,
} as any)
const SettingsCronJobIdRoute = SettingsCronJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => SettingsCronRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/cron': typeof SettingsCronRouteWithChildren
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/cron/$jobId': typeof SettingsCronJobIdRoute
  '/settings/cron/': typeof SettingsCronIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/': typeof ChatIndexRoute
  '/settings/cron/$jobId': typeof SettingsCronJobIdRoute
  '/settings/cron': typeof SettingsCronIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/cron': typeof SettingsCronRouteWithChildren
  '/settings/general': typeof SettingsGeneralRoute
  '/_chat/': typeof ChatIndexRoute
  '/settings/cron/$jobId': typeof SettingsCronJobIdRoute
  '/settings/cron/': typeof SettingsCronIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$threadId'
    | '/settings/archived'
    | '/settings/cron'
    | '/settings/general'
    | '/settings/cron/$jobId'
    | '/settings/cron/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/'
    | '/settings/cron/$jobId'
    | '/settings/cron'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/$threadId'
    | '/settings/archived'
    | '/settings/cron'
    | '/settings/general'
    | '/_chat/'
    | '/settings/cron/$jobId'
    | '/settings/cron/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cron': {
      id: '/settings/cron'
      path: '/cron'
      fullPath: '/settings/cron'
      preLoaderRoute: typeof SettingsCronRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/cron/': {
      id: '/settings/cron/'
      path: '/'
      fullPath: '/settings/cron/'
      preLoaderRoute: typeof SettingsCronIndexRouteImport
      parentRoute: typeof SettingsCronRoute
    }
    '/settings/cron/$jobId': {
      id: '/settings/cron/$jobId'
      path: '/$jobId'
      fullPath: '/settings/cron/$jobId'
      preLoaderRoute: typeof SettingsCronJobIdRouteImport
      parentRoute: typeof SettingsCronRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsCronRouteChildren {
  SettingsCronJobIdRoute: typeof SettingsCronJobIdRoute
  SettingsCronIndexRoute: typeof SettingsCronIndexRoute
}

const SettingsCronRouteChildren: SettingsCronRouteChildren = {
  SettingsCronJobIdRoute: SettingsCronJobIdRoute,
  SettingsCronIndexRoute: SettingsCronIndexRoute,
}

const SettingsCronRouteWithChildren = SettingsCronRoute._addFileChildren(
  SettingsCronRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsCronRoute: typeof SettingsCronRouteWithChildren
  SettingsGeneralRoute: typeof SettingsGeneralRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsCronRoute: SettingsCronRouteWithChildren,
  SettingsGeneralRoute: SettingsGeneralRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
