/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsTasksRouteImport } from './routes/settings.tasks'
import { Route as SettingsScheduledTasksRouteImport } from './routes/settings.scheduled-tasks'
import { Route as SettingsRunsRouteImport } from './routes/settings.runs'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as SettingsTasksIndexRouteImport } from './routes/settings.tasks.index'
import { Route as SettingsScheduledTasksIndexRouteImport } from './routes/settings.scheduled-tasks.index'
import { Route as SettingsTasksTicketIdRouteImport } from './routes/settings.tasks.$ticketId'
import { Route as SettingsScheduledTasksTaskIdRouteImport } from './routes/settings.scheduled-tasks.$taskId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsTasksRoute = SettingsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsScheduledTasksRoute = SettingsScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRunsRoute = SettingsRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsTasksIndexRoute = SettingsTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsTasksRoute,
} as any)
const SettingsScheduledTasksIndexRoute =
  SettingsScheduledTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsScheduledTasksRoute,
  } as any)
const SettingsTasksTicketIdRoute = SettingsTasksTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => SettingsTasksRoute,
} as any)
const SettingsScheduledTasksTaskIdRoute =
  SettingsScheduledTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => SettingsScheduledTasksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/runs': typeof SettingsRunsRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRouteWithChildren
  '/settings/tasks': typeof SettingsTasksRouteWithChildren
  '/settings/scheduled-tasks/$taskId': typeof SettingsScheduledTasksTaskIdRoute
  '/settings/tasks/$ticketId': typeof SettingsTasksTicketIdRoute
  '/settings/scheduled-tasks/': typeof SettingsScheduledTasksIndexRoute
  '/settings/tasks/': typeof SettingsTasksIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteWithChildren
  '/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/runs': typeof SettingsRunsRoute
  '/': typeof ChatIndexRoute
  '/settings/scheduled-tasks/$taskId': typeof SettingsScheduledTasksTaskIdRoute
  '/settings/tasks/$ticketId': typeof SettingsTasksTicketIdRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksIndexRoute
  '/settings/tasks': typeof SettingsTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/runs': typeof SettingsRunsRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRouteWithChildren
  '/settings/tasks': typeof SettingsTasksRouteWithChildren
  '/_chat/': typeof ChatIndexRoute
  '/settings/scheduled-tasks/$taskId': typeof SettingsScheduledTasksTaskIdRoute
  '/settings/tasks/$ticketId': typeof SettingsTasksTicketIdRoute
  '/settings/scheduled-tasks/': typeof SettingsScheduledTasksIndexRoute
  '/settings/tasks/': typeof SettingsTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/runs'
    | '/settings/scheduled-tasks'
    | '/settings/tasks'
    | '/settings/scheduled-tasks/$taskId'
    | '/settings/tasks/$ticketId'
    | '/settings/scheduled-tasks/'
    | '/settings/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/runs'
    | '/'
    | '/settings/scheduled-tasks/$taskId'
    | '/settings/tasks/$ticketId'
    | '/settings/scheduled-tasks'
    | '/settings/tasks'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/_chat/$threadId'
    | '/settings/archived'
    | '/settings/general'
    | '/settings/runs'
    | '/settings/scheduled-tasks'
    | '/settings/tasks'
    | '/_chat/'
    | '/settings/scheduled-tasks/$taskId'
    | '/settings/tasks/$ticketId'
    | '/settings/scheduled-tasks/'
    | '/settings/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/tasks': {
      id: '/settings/tasks'
      path: '/tasks'
      fullPath: '/settings/tasks'
      preLoaderRoute: typeof SettingsTasksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/scheduled-tasks': {
      id: '/settings/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/settings/scheduled-tasks'
      preLoaderRoute: typeof SettingsScheduledTasksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/runs': {
      id: '/settings/runs'
      path: '/runs'
      fullPath: '/settings/runs'
      preLoaderRoute: typeof SettingsRunsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/tasks/': {
      id: '/settings/tasks/'
      path: '/'
      fullPath: '/settings/tasks/'
      preLoaderRoute: typeof SettingsTasksIndexRouteImport
      parentRoute: typeof SettingsTasksRoute
    }
    '/settings/scheduled-tasks/': {
      id: '/settings/scheduled-tasks/'
      path: '/'
      fullPath: '/settings/scheduled-tasks/'
      preLoaderRoute: typeof SettingsScheduledTasksIndexRouteImport
      parentRoute: typeof SettingsScheduledTasksRoute
    }
    '/settings/tasks/$ticketId': {
      id: '/settings/tasks/$ticketId'
      path: '/$ticketId'
      fullPath: '/settings/tasks/$ticketId'
      preLoaderRoute: typeof SettingsTasksTicketIdRouteImport
      parentRoute: typeof SettingsTasksRoute
    }
    '/settings/scheduled-tasks/$taskId': {
      id: '/settings/scheduled-tasks/$taskId'
      path: '/$taskId'
      fullPath: '/settings/scheduled-tasks/$taskId'
      preLoaderRoute: typeof SettingsScheduledTasksTaskIdRouteImport
      parentRoute: typeof SettingsScheduledTasksRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsScheduledTasksRouteChildren {
  SettingsScheduledTasksTaskIdRoute: typeof SettingsScheduledTasksTaskIdRoute
  SettingsScheduledTasksIndexRoute: typeof SettingsScheduledTasksIndexRoute
}

const SettingsScheduledTasksRouteChildren: SettingsScheduledTasksRouteChildren =
  {
    SettingsScheduledTasksTaskIdRoute: SettingsScheduledTasksTaskIdRoute,
    SettingsScheduledTasksIndexRoute: SettingsScheduledTasksIndexRoute,
  }

const SettingsScheduledTasksRouteWithChildren =
  SettingsScheduledTasksRoute._addFileChildren(
    SettingsScheduledTasksRouteChildren,
  )

interface SettingsTasksRouteChildren {
  SettingsTasksTicketIdRoute: typeof SettingsTasksTicketIdRoute
  SettingsTasksIndexRoute: typeof SettingsTasksIndexRoute
}

const SettingsTasksRouteChildren: SettingsTasksRouteChildren = {
  SettingsTasksTicketIdRoute: SettingsTasksTicketIdRoute,
  SettingsTasksIndexRoute: SettingsTasksIndexRoute,
}

const SettingsTasksRouteWithChildren = SettingsTasksRoute._addFileChildren(
  SettingsTasksRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsRunsRoute: typeof SettingsRunsRoute
  SettingsScheduledTasksRoute: typeof SettingsScheduledTasksRouteWithChildren
  SettingsTasksRoute: typeof SettingsTasksRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsRunsRoute: SettingsRunsRoute,
  SettingsScheduledTasksRoute: SettingsScheduledTasksRouteWithChildren,
  SettingsTasksRoute: SettingsTasksRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
